# 2. Basic field deployment requirements

Three basic components for are required for every installation – power, instrumentation, and a cellular modem. 

## 2.1. Power system

The power system must be capable of providing power to the IFCB as well as the communication equipment. We use an AC/DC convertor with a power output of 77W, which can power both the IFCB (which needs 35W of power) as well as a modem/router (https://www.digikey.com/product-detail/en/mean-well-usa-inc/RS-75-24/1866-4160-ND/7706195). This can be plugged directly into a power source or into a backup power supply capable of providing battery power.

These systems can be very basic or more elaborate. When working on land or where the IFCB is constantly monitored e.g. in the lab or aboard a research vessel powered by AC power supply. Power cycling the IFCB for troubleshooting is simple— the instrument can be unplugged/plugged to restart the operating system and the software. 

If using shore power that is not reliable a backup power source like a UPS (uninterrupted power supply) can be used. Our lab uses an advanced UPS systems with remote monitoring and controlling capabilities, which can be useful in case of power interruptions for a graceful shutdown of the IFCB, or for power cycling the IFCB. We use the APC Smart-UPS 1500VA LCD with network card (https://www.apc.com/shop/us/en/products/APC-Smart-UPS-1500VA-LCD-120V-with-Network-Card/P-SMT1500NC). The network card in the UPS allows us to remotely monitor the power supply to the IFCB, ambient temperature around the IFCB power supply box, and turn power on/off to two different sets of UPS outlets to power cycle the IFCB for troubleshooting. This back-up power supply is capable of providing 5 hours of battery power to the IFCB in case of interruption in shore power. It can be operated between 0-60 ℃ ambient temperatures. 

For our remote operations we enclose the UPS, along with the IFCB power supply and modem/router inside a NEMA-4 certified box near shore power supply. The NEMA-4 certified box has ports drilled into its side to thread the UPS power cable out of it and to thread the IFCB communication cable inside it. Both the access ports are fitted with cable glands and rubber stoppers around the cables to make the box as weather-proof as possible![IMG_20200204_161338](README.assets/IMG_20200204_161338.jpg)

More elaborate systems for autonomous deployment can be used that include on board power generation and remote battery monitoring. For our PhytO-arm project the setup consists of an array of 2-3 solar panels which charge batteries that provide continuous power to the IFCB. A controller is connected to the solar array to remotely query the amount of charge the solar panels are providing to the battery. The controller communicates through a cellular modem connection, and in the event of inadequate solar charging to the batteries, back up power can be provided by a gas generator to ensure a continuous supply of power to the IFCB.

## 2.2. Instrumentation

The instrument itself is contained in a pressure housing to protect the internal mechanisms from exposure to the environment. The instrument core of the IFCB consisting of the laser, fluidics, and optical system is separate from the housing, but during deployments should be contained in the 40-m pressure-rated aluminum pressure housing. The internal core is sensitive to vibration and must be handled gently after the IFCB is in the pressure housing. Mechanical shocks, continuous vibrations, etc. can disrupt the internal alignment of the optical stack and should be considered when planning the deployment set up of the IFCB. Foam padding can be used on board research vessels where vibrations are a concern, and it is important to note tide tables when deploying off piers to ensure continuous access of water to the intake tube. The external aluminum housing is susceptible to anodization and      pitting due to oxidization. Anti-biofouling paint, anodes etc. can be used to avoid damaging the housing during moored deployments. 

## 2.3. Cellular modem

A cellular modem is required for remote access to monitor the instrument, adjust settings through the IFCBacquire software, and for telemetry of data to shore for automated analysis and sharing. Remote access to the IFCB is possible through Windows remote desktop if using the Windows OS, and through a websocket connection with the Linux OS version of the IFCBacquire software. If security is a concern and strong firewalls do not permit the use of Windows Remote Desktop, the IFCB CPU can be partitioned with a Linux OS. The Linux OS uses a websocket connection with a client-server-client set up for the IFCBacquire software. 

In most applications we use a modem/router because sufficient bandwidth is not available at site. A SIM card with a fixed IP /static IP address and with 30-40 Gb/month of data is used with a modem/router. The modem/router needs a one-time configuration and then systems can be moved from one ship or remote installation site to another. 

We use a modem manufactured by Sierra Wireless— the Airlink MP70 LTE-Advanced with wifi (https://www.amazon.com/Sierra-Wireless-AirLink-Performance-LTE-Advanced/dp/B01FV7ZUCO/ref=sr_1_2?crid=210EQR4SLQZCT&keywords=mp70+sierra+wireless&qid=1580924010&sprefix=mp70+%2Cundefined%2C144&sr=8-2). This is a very hardy system and can be operated between -20 to 60 ℃. It has the capabilities of both modem and router, and has advanced router configuration capabilities which can be utilized locally or remotely.

The MP70 is used in conjunction with an antenna with a 20-ft cable, which allows for the antenna to be fixed at a location with optimum cell coverage (https://www.amazon.com/Wireless-AirLink-6001197-SharkFin-Antenna/dp/B07JVLGXV9/ref=pd_sbs_147_1/144-6071161-3794129?_encoding=UTF8&pd_rd_i=B07JVLGXV9&pd_rd_r=8d15b79f-44be-4f61-8f01-bab73e69a1c1&pd_rd_w=QIaLI&pd_rd_wg=TCuSg&pf_rd_p=e962d679-e150-4018-85b7-d5551b761b80&pf_rd_r=W1WEMQP6PHFRP78Z8XB9&psc=1&refRID=W1WEMQP6PHFRP78Z8XB9).

Other, lower-grade units can be used in the place of the MP70. But crucial functions like the capability of using multiple SIM cards and remotely switch between SIM cards, ability to configure the router locally (through Wi-Fi) or remotely (through LAN connection), the ability to attach multiple devices to the MP70 and assign multiple public and private ports to each device, and restrict remote access to the IFCB to only pre-designated IP addresses make the MP70 the ideal choice. 

The MP70 can be used both locally and remotely to access the IFCB, continuously transfer data from IFCB to shore, and monitor the backup power supply system. The MP70 is also capable of providing GPS data which can be useful when deploying on research vessels.
